{% set name = "locan" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/locan-{{ version }}.tar.gz
  sha256: 292ebc7061f483a7a31a13c2fcdef49b659c679fc8f9f5473b82321724d7b399

build:
  skip: true  # [py<39]
  entry_points:
    - locan = locan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - asdf
    - tifffile
    - ruamel.yaml
    - fast-histogram
    - boost-histogram
    - lmfit
    - protobuf <5
    - shapely !=2.0.0,!=2.0.1
    - networkx
    - scikit-learn
    - scikit-image
    - matplotlib-base
    - scipy
    - pandas
    - numpy >1.20.0
    - tqdm
    - cython
    - tomli >=1.1.0  # [py<311]
    - qtpy !=2.3.0
    - typing-extensions
    - lazy_loader >=0.3

test:
  imports:
    - locan
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - locan --help
    - locan test

about:
  home: https://github.com/super-resolution/Locan
  summary: Analysis software for single-molecule localization microscopy
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://locan.readthedocs.io
  dev_url: https://github.com/super-resolution/Locan

extra:
  recipe-maintainers:
    - sdoose
