{% set name = "locan" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/locan-{{ version }}.tar.gz
  sha256: 03aaccd2fa502b35c4bc989daf88baf12fb655e9521778fab5d991cb70f5596d

build:
  skip: true  # [py<39]
  entry_points:
    - locan = locan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python
    - asdf
    - boost-histogram
    - cython
    - fast-histogram
    - lazy_loader >=0.3
    - lmfit
    - matplotlib-base
    - networkx
    - numpy >1.20.0
    - pandas
    - protobuf >6.31.1
    - qtpy !=2.3.0
    - ruamel.yaml
    - scikit-image
    - scikit-learn
    - scipy
    - shapely !=2.0.0,!=2.0.1
    - tifffile
    - tomli >=1.1.0  # [py<311]
    - tqdm
    - typing-extensions

test:
  imports:
    - locan
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - locan --help
    - locan test

about:
  home: https://github.com/super-resolution/Locan
  summary: Analysis software for single-molecule localization microscopy
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://locan.readthedocs.io
  dev_url: https://github.com/super-resolution/Locan

extra:
  recipe-maintainers:
    - sdoose
