{% set name = "locan" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/locan-{{ version }}.tar.gz
  sha256: 15b829c2d1241f262764a698b770d0651866eac6964244dc170419d72c7a65be

build:
  skip: true  # [py<39]
  entry_points:
    - locan = locan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - asdf
    - tifffile
    - ruamel.yaml
    - fast-histogram
    - boost-histogram
    - lmfit
    - protobuf
    - shapely !=2.0.0,!=2.0.1
    - networkx
    - scikit-learn
    - scikit-image
    - matplotlib-base !=3.8.0
    - scipy
    - pandas
    - numpy >1.20.0
    - tqdm
    - cython
    - tomli >=1.1.0  # [py<311]
    - qtpy !=2.3.0
    - typing-extensions

test:
  imports:
    - locan
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - locan --help

about:
  home: https://github.com/super-resolution/Locan
  summary: Analysis software for single-molecule localization microscopy
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://locan.readthedocs.io
  dev_url: https://github.com/super-resolution/Locan

extra:
  recipe-maintainers:
    - sdoose
